// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client/matrix.proto

/*
Package matrixProtos_Client is a generated protocol buffer package.

It is generated from these files:
	client/matrix.proto

It has these top-level messages:
	VersionsResponse
	Version
	VersionRequest
	LoginRequest
	LoginResponse
	LoginError
*/
package matrixProtos_Client

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VersionsResponse struct {
	Versions []*Version `protobuf:"bytes,1,rep,name=versions" json:"versions,omitempty"`
}

func (m *VersionsResponse) Reset()                    { *m = VersionsResponse{} }
func (m *VersionsResponse) String() string            { return proto.CompactTextString(m) }
func (*VersionsResponse) ProtoMessage()               {}
func (*VersionsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *VersionsResponse) GetVersions() []*Version {
	if m != nil {
		return m.Versions
	}
	return nil
}

type Version struct {
	Version string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
}

func (m *Version) Reset()                    { *m = Version{} }
func (m *Version) String() string            { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()               {}
func (*Version) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Version) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type VersionRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *VersionRequest) Reset()                    { *m = VersionRequest{} }
func (m *VersionRequest) String() string            { return proto.CompactTextString(m) }
func (*VersionRequest) ProtoMessage()               {}
func (*VersionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *VersionRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type LoginRequest struct {
	Type     string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	User     string `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	Medium   string `protobuf:"bytes,4,opt,name=medium" json:"medium,omitempty"`
	Address  string `protobuf:"bytes,5,opt,name=address" json:"address,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LoginRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *LoginRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetMedium() string {
	if m != nil {
		return m.Medium
	}
	return ""
}

func (m *LoginRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type LoginResponse struct {
	AccessToken  string `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	HomeServer   string `protobuf:"bytes,2,opt,name=home_server,json=homeServer" json:"home_server,omitempty"`
	UserId       string `protobuf:"bytes,3,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	RefreshToken string `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken" json:"refresh_token,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *LoginResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *LoginResponse) GetHomeServer() string {
	if m != nil {
		return m.HomeServer
	}
	return ""
}

func (m *LoginResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *LoginResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type LoginError struct {
	Errcode string `protobuf:"bytes,1,opt,name=errcode" json:"errcode,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *LoginError) Reset()                    { *m = LoginError{} }
func (m *LoginError) String() string            { return proto.CompactTextString(m) }
func (*LoginError) ProtoMessage()               {}
func (*LoginError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *LoginError) GetErrcode() string {
	if m != nil {
		return m.Errcode
	}
	return ""
}

func (m *LoginError) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*VersionsResponse)(nil), "matrixProtos_Client.VersionsResponse")
	proto.RegisterType((*Version)(nil), "matrixProtos_Client.Version")
	proto.RegisterType((*VersionRequest)(nil), "matrixProtos_Client.VersionRequest")
	proto.RegisterType((*LoginRequest)(nil), "matrixProtos_Client.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "matrixProtos_Client.LoginResponse")
	proto.RegisterType((*LoginError)(nil), "matrixProtos_Client.LoginError")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for VersionsService service

type VersionsServiceClient interface {
	Versions(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionsResponse, error)
}

type versionsServiceClient struct {
	cc *grpc.ClientConn
}

func NewVersionsServiceClient(cc *grpc.ClientConn) VersionsServiceClient {
	return &versionsServiceClient{cc}
}

func (c *versionsServiceClient) Versions(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionsResponse, error) {
	out := new(VersionsResponse)
	err := grpc.Invoke(ctx, "/matrixProtos_Client.VersionsService/Versions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VersionsService service

type VersionsServiceServer interface {
	Versions(context.Context, *VersionRequest) (*VersionsResponse, error)
}

func RegisterVersionsServiceServer(s *grpc.Server, srv VersionsServiceServer) {
	s.RegisterService(&_VersionsService_serviceDesc, srv)
}

func _VersionsService_Versions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionsServiceServer).Versions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matrixProtos_Client.VersionsService/Versions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionsServiceServer).Versions(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VersionsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "matrixProtos_Client.VersionsService",
	HandlerType: (*VersionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Versions",
			Handler:    _VersionsService_Versions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "client/matrix.proto",
}

// Client API for LoginService service

type LoginServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type loginServiceClient struct {
	cc *grpc.ClientConn
}

func NewLoginServiceClient(cc *grpc.ClientConn) LoginServiceClient {
	return &loginServiceClient{cc}
}

func (c *loginServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := grpc.Invoke(ctx, "/matrixProtos_Client.LoginService/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LoginService service

type LoginServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
}

func RegisterLoginServiceServer(s *grpc.Server, srv LoginServiceServer) {
	s.RegisterService(&_LoginService_serviceDesc, srv)
}

func _LoginService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matrixProtos_Client.LoginService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LoginService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "matrixProtos_Client.LoginService",
	HandlerType: (*LoginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _LoginService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "client/matrix.proto",
}

func init() { proto.RegisterFile("client/matrix.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0x4b, 0xeb, 0x40,
	0x14, 0xc5, 0xc9, 0xeb, 0xdf, 0x77, 0xdb, 0xbe, 0xf7, 0x98, 0x3e, 0x34, 0x14, 0xc1, 0x36, 0x45,
	0x28, 0x2e, 0x2a, 0xd4, 0x8d, 0x0b, 0x77, 0xe2, 0x42, 0x28, 0x22, 0x55, 0xba, 0x34, 0xc4, 0xe4,
	0x6a, 0x07, 0x4d, 0x27, 0xde, 0x9b, 0x56, 0xdd, 0xfb, 0x05, 0xfc, 0xc6, 0x32, 0x93, 0x99, 0x50,
	0xa1, 0x74, 0x37, 0xe7, 0xd7, 0x73, 0x6f, 0x4f, 0xe6, 0x0c, 0x74, 0xe3, 0x17, 0x89, 0xcb, 0xfc,
	0x24, 0x8d, 0x72, 0x92, 0xef, 0xe3, 0x8c, 0x54, 0xae, 0x44, 0xb7, 0x50, 0x37, 0x5a, 0x70, 0x78,
	0x61, 0x1c, 0xc1, 0x14, 0xfe, 0xcd, 0x91, 0x58, 0xaa, 0x25, 0xcf, 0x90, 0x33, 0xb5, 0x64, 0x14,
	0x67, 0xd0, 0x5c, 0x5b, 0xe6, 0x7b, 0xfd, 0xca, 0xa8, 0x35, 0x39, 0x18, 0x6f, 0x99, 0x1d, 0xdb,
	0xc1, 0x59, 0xe9, 0x0e, 0x86, 0xd0, 0xb0, 0x50, 0xf8, 0xd0, 0xb0, 0xd8, 0xf7, 0xfa, 0xde, 0xe8,
	0xf7, 0xcc, 0xc9, 0xe0, 0x18, 0xfe, 0xb8, 0x49, 0x7c, 0x5d, 0x21, 0xe7, 0xda, 0x1b, 0x25, 0x09,
	0x21, 0xb3, 0xf3, 0x5a, 0x19, 0x7c, 0x7a, 0xd0, 0x9e, 0xaa, 0x27, 0x59, 0x5a, 0x05, 0x54, 0xf3,
	0x8f, 0x0c, 0xad, 0xcf, 0x9c, 0x35, 0x5b, 0x31, 0x92, 0xff, 0xab, 0x60, 0xfa, 0x2c, 0x7a, 0xd0,
	0xcc, 0x22, 0xe6, 0x37, 0x45, 0x89, 0x5f, 0x31, 0xbc, 0xd4, 0x62, 0x0f, 0xea, 0x29, 0x26, 0x72,
	0x95, 0xfa, 0x55, 0xf3, 0x8b, 0x55, 0x9b, 0x31, 0x6a, 0x3f, 0x63, 0x7c, 0x79, 0xd0, 0xb1, 0x31,
	0xec, 0x1d, 0x0d, 0xa0, 0x1d, 0xc5, 0x31, 0x32, 0x87, 0xb9, 0x7a, 0x46, 0xf7, 0x8d, 0xad, 0x82,
	0xdd, 0x69, 0x24, 0x0e, 0xa1, 0xb5, 0x50, 0x29, 0x86, 0x8c, 0xb4, 0x2e, 0xd3, 0x81, 0x46, 0xb7,
	0x86, 0x88, 0x7d, 0x68, 0xe8, 0xac, 0xa1, 0x74, 0x11, 0xeb, 0x5a, 0x5e, 0x25, 0x62, 0x08, 0x1d,
	0xc2, 0x47, 0x42, 0x5e, 0xd8, 0xed, 0x45, 0xce, 0xb6, 0x85, 0x66, 0x7d, 0x70, 0x0e, 0x60, 0x22,
	0x5d, 0x12, 0x29, 0xd2, 0xd9, 0x91, 0x28, 0x56, 0x89, 0xbb, 0x1a, 0x27, 0xc5, 0x7f, 0xa8, 0xa1,
	0xb6, 0xd8, 0x00, 0x85, 0x98, 0x48, 0xf8, 0xeb, 0x7a, 0xd7, 0x69, 0x64, 0x8c, 0x62, 0x0e, 0x4d,
	0x87, 0xc4, 0x70, 0x67, 0xe1, 0x45, 0x17, 0xbd, 0xa3, 0x5d, 0xa6, 0xf2, 0x39, 0x4d, 0xee, 0x6d,
	0x85, 0xee, 0x7f, 0xae, 0xa1, 0x66, 0xb4, 0x18, 0x6c, 0x9d, 0xdf, 0xac, 0xbb, 0x17, 0xec, 0xb2,
	0x14, 0xfb, 0x1f, 0xea, 0xe6, 0x79, 0x9f, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x92, 0xea, 0x6a,
	0xb7, 0xf5, 0x02, 0x00, 0x00,
}
